gg:
  jte:
    development-mode: true

spring:
  application:
    name: GenCin

  datasource:
    url: jdbc:postgresql://198.74.53.107:5432/gencin
    username: lk
    password: password_lk
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  springdoc:
    api-docs:
      path: /v3/api-docs
    swagger-ui:
      path: /swagger-ui.html

  data:
    rest:
      detection-strategy: annotated

jwt:
  secret: "vOujlRpK!vT4UeY$?c%5Bj8pZs6DqLfMn"
